### ISSUE TITLE
Lambda function source code

### ISSUE THREAD

**Issue by korrosivesec** [shabarkin/pointer#2]
Awesome work on this project!

Anyway you could also include the source code for the lambda function?

**Comment by ocbrollingpaper** [comment]
I think it's more than clear
`Pointer has a configure subcommand for automatic deployment of IAM, Lambda, SQS, DynamoDB, and Autoscaling services. `

**Comment by korrosivesec** [comment]
> I think it's more than clear `Pointer has a configure subcommand for automatic deployment of IAM, Lambda, SQS, DynamoDB, and Autoscaling services. `

Not sure how this is relevant to my request.  

I get that the configure command automatically provisions things in AWS.  But without reversing the ELF binary deployed from function.zip into the Lambda function, I have no idea what it's actually doing and therefore can't trust it.

https://github.com/shabarkin/pointer/blob/8c215f76e505bb9fff5b71c3a8e71c02ab53136b/utils/cloud.go#L77

I'm simply asking if we could get the source code for compiled ELF binary to verify functionality.

**Comment by shabarkin** [comment]
Yes, you can DM me @shabarkin on telegram I will share, @korrosivesec

**Comment by shabarkin** [comment]
Source code of the lambda is added
